import "./globals.css";
import type { Metadata } from "next";
import { Inter } from "next/font/google";
import localFont from "next/font/local";
import { NavBar } from "@/components/nav-bar";
import { Footer } from "@/components/footer";

// Keep the Inter font
const inter = Inter({ subsets: ["latin"] });

// Add your local font
const myFont = localFont({
  src: [
    {
      path: "../public/fonts/LEGO.ttf",
      weight: "400",
      style: "normal",
    },
  ],
  display: "swap",
  variable: "--font-custom",
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en" className={myFont.className}>
      <body className={`${myFont.variable} font-custom`}>
        <NavBar />
        {children}
        <Footer />
      </body>
    </html>
  );
}
